name: Deploy Laravel on cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_dsa
        chmod 600 ~/.ssh/id_dsa
        ssh-keyscan -p 21098 -H ${{ secrets.CPANEL_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to cPanel
      run: |
        ssh -oHostKeyAlgorithms=+ssh-dss -p 21098 ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }} << 'EOF'
          cd ${{ secrets.CPANEL_PATH }}

          echo "Checking for unstaged changes..."
          if [[ -n $(git status --porcelain) ]]; then
            echo "Stashing local changes..."
            git stash
          fi

          echo "Pulling latest code from GitHub..."
          git pull origin main --rebase || { echo "Git pull failed"; exit 1; }

          echo "Installing dependencies..."
          composer install --no-interaction --prefer-dist --no-dev --optimize-autoloader || { echo "Composer install failed"; exit 1; }

          echo "Running migrations..."
          php artisan migrate --force || { echo "Migration failed"; exit 1; }

          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan queue:restart

          echo "Deployment completed successfully!"
        EOF
      env:
        CPANEL_USER: ${{ secrets.CPANEL_USER }}
        CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
        CPANEL_PATH: ${{ secrets.CPANEL_PATH }}
