name: Deploy Laravel on cPanel

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to cPanel
      run: |
        echo "Starting deployment to cPanel..."

        # Connect to the cPanel server via SSH and execute deployment commands
        ssh -o StrictHostKeyChecking=no ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }} << 'EOF'

          # Navigate to Laravel app directory
          cd ${{ secrets.CPANEL_PATH }}

          # Backup the current working commit
          echo "Backing up current working commit..."
          git rev-parse HEAD > last_successful_commit.txt

          # Pull the latest code
          echo "Fetching new changes..."
          git pull origin main || { echo "Git pull failed"; exit 1; }

          # Install dependencies
          echo "Installing composer dependencies..."
          composer install --no-interaction --prefer-dist --optimize-autoloader || { echo "Composer install failed"; exit 1; }

          # Run migrations
          echo "Running migrations..."
          php artisan migrate --force || { echo "Migration failed"; exit 1; }

          # Clear and cache configuration
          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache

          # Restart queue workers (if applicable)
          php artisan queue:restart

          echo "Deployment completed successfully!"

        EOF
      env:
        CPANEL_USER: ${{ secrets.CPANEL_USER }}
        CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
        CPANEL_PATH: ${{ secrets.CPANEL_PATH }}

    - name: Rollback if deployment fails
      if: failure()
      run: |
        echo "Deployment failed! Rolling back..."
        ssh -o StrictHostKeyChecking=no ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }} << 'EOF'
          cd ${{ secrets.CPANEL_PATH }}

          # Revert to last successful commit
          if [ -f last_successful_commit.txt ]; then
            LAST_COMMIT=$(cat last_successful_commit.txt)
            echo "Rolling back to $LAST_COMMIT..."
            git reset --hard $LAST_COMMIT
          else
            echo "No previous commit found, rollback not possible."
          fi
        EOF
